### ISSUE TITLE
`validateProtocol` is not isomorphic

### ISSUE THREAD

**Issue by sebastienlevert** [microsoft/kiota-typescript#394]
When using `validateProtocol` on NodeJS, we get errors around `window is not defined`.

I am using the following kiota command to generate my client : `kiota generate -l typescript -o nytmoviereviews -d https://raw.githubusercontent.com/nytimes/public_api_specs/master/movie_reviews/movie_reviews_v2.json -c NytMovieClient -n Nyt`

```
/home/slevert/source/sebastienlevert/KiotaApp/src/js/node_modules/@microsoft/kiota-abstractions/src/authentication/validateProtocol.ts:8
    return window && window.location && (window.location.protocol as string).toLowerCase() !== 'https:';
    ^
ReferenceError: window is not defined
    at windowUrlStartsWithHttps (/home/slevert/source/sebastienlevert/KiotaApp/src/js/node_modules/@microsoft/kiota-abstractions/src/authentication/validateProtocol.ts:8:5)
    at validateProtocol (/home/slevert/source/sebastienlevert/KiotaApp/src/js/node_modules/@microsoft/kiota-abstractions/src/authentication/validateProtocol.ts:2:60)
    at ApiKeyAuthenticationProvider.authenticateRequest (/home/slevert/source/sebastienlevert/KiotaApp/src/js/ApiKeyAuthenticationProvider.ts:37:21)
    at FetchRequestAdapter.<anonymous> (/home/slevert/source/sebastienlevert/KiotaApp/src/js/node_modules/@microsoft/kiota-http-fetchlibrary/dist/cjs/src/fetchRequestAdapter.js:250:47)
    at Generator.next (<anonymous>)
    at /home/slevert/source/sebastienlevert/KiotaApp/src/js/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/slevert/source/sebastienlevert/KiotaApp/src/js/node_modules/tslib/tslib.js:114:16)
    at FetchRequestAdapter.getHttpResponseMessage (/home/slevert/source/sebastienlevert/KiotaApp/src/js/node_modules/@microsoft/kiota-http-fetchlibrary/dist/cjs/src/fetchRequestAdapter.js:241:72)
    at FetchRequestAdapter.<anonymous> (/home/slevert/source/sebastienlevert/KiotaApp/src/js/node_modules/@microsoft/kiota-http-fetchlibrary/dist/cjs/src/fetchRequestAdapter.js:110:41)
```

**Comment by sebastienlevert** [comment]
To be validated, but I don't think it's the case anymore. I don't run in any of these challenges.
