### ISSUE TITLE
getCollectionOfObjectValues throws: TypeError: Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by pschaeflein** [microsoft/kiota-typescript#820]
For an array property marked as nullable, the json serializer does not check for null.

Versions:
  "@microsoft/kiota-abstractions": "^1.0.0-preview.26",
  "@microsoft/kiota-serialization-json": "^1.0.0-preview.25",

Relevant OpenApi document snippets (note that the `foos` property is nullable):
```json
"Models.FooObjectResponse": {
  "type": "object",
  "properties": {
    "foos": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Models.FooResponse"
      },
      "nullable": true
    }
  },
  "additionalProperties": false
},

"Models.FooResponse": {
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "bars": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Models.BarResponse"
      },
      "nullable": true
    }
  },
  "additionalProperties": false
},

"Models.BarResponse": {
  "type": "object",
  "properties": {
    "propA": {
     "type": "string"
    },
    "propB": {
      "type": "string",
      "nullable": true
    },
    "propC": {
      "type": "string",
      "format": "date-time",
      "nullable": true
    }
  },
  "additionalProperties": false
},
```

Generated model:
```typescript
export interface FooObjectResponse extends Parsable {
    /**
     * The foos property
     */
    foos?: FooResponse[] | undefined;
}

export interface FooResponse extends Parsable {
    /**
     * The id property
     */
    id?: string | undefined;
    /**
     * The bars property
     */
    bars?: BarResponse[] | undefined;
}

export interface BarResponse extends Parsable {
    /**
     * The propA property
     */
    propA?: string | undefined;
    /**
     * The propB property
     */
    propB?: string | undefined;
    /**
     * The propC property
     */
    propC?: Date | undefined;
}

```

Response:
```json
{
    "foos": [
        {
            "id": "b089d1f1-e527-4b8a-ba96-094922af6e40",
            "bars": null
        }
    ]
}
```

Callstack:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'map')
    at r.getCollectionOfObjectValues (jsonParseNode.js:49:18)
    at bars (deserializeIntoFooResponse.ts:10:64)
    at jsonParseNode.js:70:21
    at Array.forEach (<anonymous>)
    at r.assignFieldValues (jsonParseNode.js:67:44)
    at r.getObjectValue (jsonParseNode.js:57:18)
    at jsonParseNode.js:50:31
    at Array.map (<anonymous>)
    at r.getCollectionOfObjectValues (jsonParseNode.js:50:18)
    at tenants (deserializeIntoFooObjectResponse.ts:9:59)
```

**Comment by baywet** [comment]
Hi @pschaeflein 
Thanks for reporting this. This section most likely needs defensive programming (i.e. if it's null or the map method, which would come with a collection, is absent, return undefined).
https://github.com/microsoft/kiota-typescript/blob/b55753a66df0c4c6694b58c27fd31f0b9d7127ee/packages/serialization/json/src/jsonParseNode.ts#L64

Would you want to submit a pull request to address this issue?

**Comment by pschaeflein** [comment]
Sorry @baywet, but I can't follow the logic in that method at all. Any change I make would be just hacking away...

**Comment by baywet** [comment]
no worries, assigning to @koros who should be in a better position to implement a fix then.
